version: '2'

services:         
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

    expose:
        - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
        - "5434:5434"
    command: -p 5434