version: '2'

services:         
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=db

    expose:
        - "6666" # Publishes 6666 to other containers but NOT to host machine
    ports:
        - "6666:6666"
    command: -p 6666
